### ISSUE TITLE
Installation error with pip 

### ISSUE THREAD

**Issue by mafortin** [benoitberanger/niix2bids#4]
Hi! As the issue title mentions, I am unable to install niix2bids on Ubuntu 18.04.

I did the recommended standard installation procedure as explained here in Github. 

I tried with two different **new** virtual environments. One with python 3.9 and one with 3.10. Both resulted in the same error message with pip. 

It looks like the same error as explained in the "Known issues" section about pip but I did the steps to avoid that error, and still got it.

Here is the error message posted:

"""
(niix2bids) marcantf@mrphys-gpu1:~$ pip install git+https://github.com/benoitberanger/niix2bids
Collecting git+https://github.com/benoitberanger/niix2bids

  Cloning https://github.com/benoitberanger/niix2bids to /tmp/pip-req-build-5dx6lbcs
  Running command git clone --filter=blob:none --quiet https://github.com/benoitberanger/niix2bids /tmp/pip-req-build-5dx6lbcs
  Resolved https://github.com/benoitberanger/niix2bids to commit 80d2abd3c6e2b37a167a19bd741c1e465b6ca375
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Warning: 'classifiers' should be a list, got type 'tuple'
      /home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/dist.py:530: UserWarning: Normalizing 'v2.0.0' to '2.0.0'
        warnings.warn(tmpl.format(**locals()))
      running egg_info
      creating /tmp/pip-pip-egg-info-sa9p1dt0/niix2bids.egg-info
      writing /tmp/pip-pip-egg-info-sa9p1dt0/niix2bids.egg-info/PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-5dx6lbcs/setup.py", line 10, in <module>
          setuptools.setup(
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 300, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 664, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1136, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "/home/marcantf/miniconda3/envs/niix2bids/lib/python3.10/site-packages/setuptools/dist.py", line 233, in write_pkg_file
          if not long_description.endswith("\n"):
      AttributeError: 'list' object has no attribute 'endswith'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"""

**Comment by benoitberanger** [comment]
Hi @mafortin ,

This the kind of error I had too, but the instructions I wrote solved the problem for me and the few other users that tried this package so far.
Are you sure you used `conda install pip` :
![image](https://user-images.githubusercontent.com/16976839/178143390-71fae113-d080-4965-b5c6-e4a476f064bf.png)

If no, could you give it a try ?
If yes, then there is a deeper problem and I have to investigate. The [setyp.py](https://github.com/benoitberanger/niix2bids/blob/master/setup.py) is very simple, and still there is a problem somewhere.

Best,
Benoît

**Comment by mafortin** [comment]
Hi @benoitberanger, yes I’m sure I did it for at least one of the two tries. Not sure for the second one though.

**Comment by benoitberanger** [comment]
I cannot reproduce the error, even though I tried on different systems : Linux Mint, Windows WSL, MacOS.

However, since the error comes from the field `long_description` in `setup.py`, let's try to change it.
Could you try to clone the repo first so you can modify a line :

```
cd /path/to/mydir/
git clone https://github.com/benoitberanger/niix2bids
conda create --name niix2bids
conda activate niix2bids
conda install pip
```
Do the modification : 
https://github.com/benoitberanger/niix2bids/blob/80d2abd3c6e2b37a167a19bd741c1e465b6ca375/setup.py#L8
`readlines` -> `read`

Then install using the local repo :
```
pip install -e niix2bids/
```

The `long_description` should be a _str_ instead of _list[str]_

**Comment by mafortin** [comment]
Hi @benoitberanger,

I can confirm the solution proposed above works! Changing f.readlines() to f.read() solved the issue! Now, niix2bids is correctly running.

**Comment by benoitberanger** [comment]
Thank you for trying this modification and making feedback !
